export const INIT_FETCH = 'INIT_FETCH';
export const FETCH_SEVICES = 'FETCH_SEVICES';
export const SERVICES_REQUEST_SUCCESS = 'SERVICES_REQUEST_SUCCESS';
export const SERVICES_REQUEST_FAILURE = 'SERVICES_REQUEST_FAILURE';
export const INIT_FETCH_SERVICE_INFO = 'INIT_FETCH_SERVICE_INFO';
export const FETCH_SERVICE_INFO = 'FETCH_SERVICE_INFO';
export const SERVICE_INFO_REQUEST_SUCCESS = 'SERVICE_INFO_REQUEST_SUCCESS';