export const INIT_FETCH = 'INIT_FETCH';
export const FETCH_SEVICES = 'FETCH_SEVICES';
export const SERVICES_REQUEST_SUCCESS = 'SERVICES_REQUEST_SUCCESS';
export const SERVICES_REQUEST_FAILURE = 'SERVICES_REQUEST_FAILURE';